/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ICityHistoryInterface extends Interface {
    getFunction(nameOrSignature: "initializePlotHistory" | "recordAetherUse" | "recordLayerAdded" | "recordOwnershipTransfer"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'initializePlotHistory', values: [BigNumberish, AddressLike, BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'recordAetherUse', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordLayerAdded', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordOwnershipTransfer', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'initializePlotHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordAetherUse', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordLayerAdded', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordOwnershipTransfer', data: BytesLike): Result;
  }

  

  export interface ICityHistory extends BaseContract {
    
    connect(runner?: ContractRunner | null): ICityHistory;
    waitForDeployment(): Promise<this>;

    interface: ICityHistoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    initializePlotHistory: TypedContractMethod<
      [plotId: BigNumberish, firstBuilder: AddressLike, faction: BigNumberish, genesisEra: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    recordAetherUse: TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordLayerAdded: TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordOwnershipTransfer: TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'initializePlotHistory'): TypedContractMethod<
      [plotId: BigNumberish, firstBuilder: AddressLike, faction: BigNumberish, genesisEra: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordAetherUse'): TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordLayerAdded'): TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordOwnershipTransfer'): TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }