/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace ICityWeaponSockets {
      
    export type TotalBonusesStruct = {minDamageBonus: BigNumberish, maxDamageBonus: BigNumberish, attackSpeedBonus: BigNumberish, critChanceBpsBonus: BigNumberish, critMultiplierBpsBonus: BigNumberish, accuracyBpsBonus: BigNumberish, rangeBonus: BigNumberish, maxDurabilityBonus: BigNumberish, armorPenBpsBonus: BigNumberish, blockChanceBpsBonus: BigNumberish, lifeStealBpsBonus: BigNumberish, energyCostBonus: BigNumberish, heatGenerationBonus: BigNumberish, stabilityBonus: BigNumberish, cooldownMsBonus: BigNumberish, projectileSpeedBonus: BigNumberish, aoeRadiusBonus: BigNumberish, enchantmentSlotsBonus: BigNumberish, materiaSlotsBonus: BigNumberish}

    export type TotalBonusesStructOutput = [minDamageBonus: bigint, maxDamageBonus: bigint, attackSpeedBonus: bigint, critChanceBpsBonus: bigint, critMultiplierBpsBonus: bigint, accuracyBpsBonus: bigint, rangeBonus: bigint, maxDurabilityBonus: bigint, armorPenBpsBonus: bigint, blockChanceBpsBonus: bigint, lifeStealBpsBonus: bigint, energyCostBonus: bigint, heatGenerationBonus: bigint, stabilityBonus: bigint, cooldownMsBonus: bigint, projectileSpeedBonus: bigint, aoeRadiusBonus: bigint, enchantmentSlotsBonus: bigint, materiaSlotsBonus: bigint] & {minDamageBonus: bigint, maxDamageBonus: bigint, attackSpeedBonus: bigint, critChanceBpsBonus: bigint, critMultiplierBpsBonus: bigint, accuracyBpsBonus: bigint, rangeBonus: bigint, maxDurabilityBonus: bigint, armorPenBpsBonus: bigint, blockChanceBpsBonus: bigint, lifeStealBpsBonus: bigint, energyCostBonus: bigint, heatGenerationBonus: bigint, stabilityBonus: bigint, cooldownMsBonus: bigint, projectileSpeedBonus: bigint, aoeRadiusBonus: bigint, enchantmentSlotsBonus: bigint, materiaSlotsBonus: bigint }
  
    }

  export interface ICityWeaponSocketsInterface extends Interface {
    getFunction(nameOrSignature: "getTotalBonuses"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getTotalBonuses', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'getTotalBonuses', data: BytesLike): Result;
  }

  

  export interface ICityWeaponSockets extends BaseContract {
    
    connect(runner?: ContractRunner | null): ICityWeaponSockets;
    waitForDeployment(): Promise<this>;

    interface: ICityWeaponSocketsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getTotalBonuses: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [ICityWeaponSockets.TotalBonusesStructOutput],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getTotalBonuses'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [ICityWeaponSockets.TotalBonusesStructOutput],
      'view'
    >;

    

    filters: {
      
    };
  }