/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ICityStatusInterface extends Interface {
    getFunction(nameOrSignature: "getDerivedStatus" | "isLayerEligible" | "recordMaintenance" | "touchActivity"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getDerivedStatus', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isLayerEligible', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordMaintenance', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'touchActivity', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'getDerivedStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isLayerEligible', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordMaintenance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'touchActivity', data: BytesLike): Result;
  }

  

  export interface ICityStatus extends BaseContract {
    
    connect(runner?: ContractRunner | null): ICityStatus;
    waitForDeployment(): Promise<this>;

    interface: ICityStatusInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getDerivedStatus: TypedContractMethod<
      [plotId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    isLayerEligible: TypedContractMethod<
      [plotId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    recordMaintenance: TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    touchActivity: TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getDerivedStatus'): TypedContractMethod<
      [plotId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isLayerEligible'): TypedContractMethod<
      [plotId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'recordMaintenance'): TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'touchActivity'): TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }