/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ICityWeaponsInterface extends Interface {
    getFunction(nameOrSignature: "mintWeapon"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'mintWeapon', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, boolean, boolean, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'mintWeapon', data: BytesLike): Result;
  }

  

  export interface ICityWeapons extends BaseContract {
    
    connect(runner?: ContractRunner | null): ICityWeapons;
    waitForDeployment(): Promise<this>;

    interface: ICityWeaponsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    mintWeapon: TypedContractMethod<
      [to: AddressLike, weaponDefinitionId: BigNumberish, rarityTier: BigNumberish, frameTier: BigNumberish, originPlotId: BigNumberish, originFaction: BigNumberish, originDistrictKind: BigNumberish, resonanceType: BigNumberish, visualVariant: BigNumberish, genesisEra: boolean, usedAether: boolean, nonce: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'mintWeapon'): TypedContractMethod<
      [to: AddressLike, weaponDefinitionId: BigNumberish, rarityTier: BigNumberish, frameTier: BigNumberish, originPlotId: BigNumberish, originFaction: BigNumberish, originDistrictKind: BigNumberish, resonanceType: BigNumberish, visualVariant: BigNumberish, genesisEra: boolean, usedAether: boolean, nonce: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }