/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IFarmingV6 {
      
    export type FarmInfoStruct = {startTime: BigNumberish, lastAccrualTime: BigNumberish, lastClaimTime: BigNumberish, boostExpiry: BigNumberish, stopTime: BigNumberish, isActive: boolean}

    export type FarmInfoStructOutput = [startTime: bigint, lastAccrualTime: bigint, lastClaimTime: bigint, boostExpiry: bigint, stopTime: bigint, isActive: boolean] & {startTime: bigint, lastAccrualTime: bigint, lastClaimTime: bigint, boostExpiry: bigint, stopTime: bigint, isActive: boolean }
  
    }

  export interface IFarmingV6Interface extends Interface {
    getFunction(nameOrSignature: "buyBoost" | "claimResources" | "getAllPending" | "getBoostMultiplier" | "getClaimableResources" | "getFarmState" | "getFarmStatusCode" | "getFarmStatusCodeV6" | "getPending" | "hasBoost" | "inpiPool" | "inpiToken" | "inpinityNFT" | "isClaimMature" | "partnershipContract" | "pitronePool" | "resourceToken" | "secondsUntilClaimable" | "startFarming" | "stopFarming" | "treasury"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'buyBoost', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimResources', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllPending', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBoostMultiplier', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getClaimableResources', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getFarmState', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getFarmStatusCode', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getFarmStatusCodeV6', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPending', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasBoost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'inpiPool', values?: undefined): string;
encodeFunctionData(functionFragment: 'inpiToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'inpinityNFT', values?: undefined): string;
encodeFunctionData(functionFragment: 'isClaimMature', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'partnershipContract', values?: undefined): string;
encodeFunctionData(functionFragment: 'pitronePool', values?: undefined): string;
encodeFunctionData(functionFragment: 'resourceToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'secondsUntilClaimable', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'startFarming', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stopFarming', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'buyBoost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimResources', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllPending', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBoostMultiplier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getClaimableResources', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFarmState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFarmStatusCode', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFarmStatusCodeV6', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPending', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasBoost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'inpiPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'inpiToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'inpinityNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isClaimMature', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'partnershipContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pitronePool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resourceToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'secondsUntilClaimable', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startFarming', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stopFarming', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
  }

  

  export interface IFarmingV6 extends BaseContract {
    
    connect(runner?: ContractRunner | null): IFarmingV6;
    waitForDeployment(): Promise<this>;

    interface: IFarmingV6Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    buyBoost: TypedContractMethod<
      [tokenId: BigNumberish, daysAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claimResources: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAllPending: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getBoostMultiplier: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getClaimableResources: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[bigint[], bigint[]] & {ids: bigint[], amounts: bigint[] }],
      'view'
    >
    

    
    getFarmState: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [IFarmingV6.FarmInfoStructOutput],
      'view'
    >
    

    
    getFarmStatusCode: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getFarmStatusCodeV6: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getPending: TypedContractMethod<
      [tokenId: BigNumberish, resourceId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    hasBoost: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    inpiPool: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    inpiToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    inpinityNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isClaimMature: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    partnershipContract: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pitronePool: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    resourceToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    secondsUntilClaimable: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    startFarming: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stopFarming: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'buyBoost'): TypedContractMethod<
      [tokenId: BigNumberish, daysAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimResources'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllPending'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getBoostMultiplier'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getClaimableResources'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[bigint[], bigint[]] & {ids: bigint[], amounts: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getFarmState'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [IFarmingV6.FarmInfoStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getFarmStatusCode'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getFarmStatusCodeV6'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPending'): TypedContractMethod<
      [tokenId: BigNumberish, resourceId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hasBoost'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'inpiPool'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'inpiToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'inpinityNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isClaimMature'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'partnershipContract'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pitronePool'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'resourceToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'secondsUntilClaimable'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'startFarming'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stopFarming'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }