/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IPiratesV6 {
      
    export type AttackDataStruct = {attacker: AddressLike, attackerTokenId: BigNumberish, targetTokenId: BigNumberish, startTime: BigNumberish, endTime: BigNumberish, resource: BigNumberish, executed: boolean, cancelled: boolean}

    export type AttackDataStructOutput = [attacker: string, attackerTokenId: bigint, targetTokenId: bigint, startTime: bigint, endTime: bigint, resource: bigint, executed: boolean, cancelled: boolean] & {attacker: string, attackerTokenId: bigint, targetTokenId: bigint, startTime: bigint, endTime: bigint, resource: bigint, executed: boolean, cancelled: boolean }
  
    }

  export interface IPiratesV6Interface extends Interface {
    getFunction(nameOrSignature: "RESOURCE_COUNT" | "buyPirateBoost" | "canAttackTarget" | "cancelOwnPendingAttack" | "executeAttack" | "farming" | "getAttack" | "getAttackCount" | "getAttackTime" | "getPirateBoostExpiry" | "getRemainingAttacksToday" | "hasPirateBoost" | "startAttack"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'RESOURCE_COUNT', values?: undefined): string;
encodeFunctionData(functionFragment: 'buyPirateBoost', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'canAttackTarget', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelOwnPendingAttack', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'executeAttack', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'farming', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAttack', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAttackCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAttackTime', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPirateBoostExpiry', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRemainingAttacksToday', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasPirateBoost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'startAttack', values: [BigNumberish, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'RESOURCE_COUNT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyPirateBoost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'canAttackTarget', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelOwnPendingAttack', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeAttack', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'farming', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAttack', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAttackCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAttackTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPirateBoostExpiry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRemainingAttacksToday', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasPirateBoost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startAttack', data: BytesLike): Result;
  }

  

  export interface IPiratesV6 extends BaseContract {
    
    connect(runner?: ContractRunner | null): IPiratesV6;
    waitForDeployment(): Promise<this>;

    interface: IPiratesV6Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    RESOURCE_COUNT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    buyPirateBoost: TypedContractMethod<
      [tokenId: BigNumberish, daysAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    canAttackTarget: TypedContractMethod<
      [attacker: AddressLike, targetTokenId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    cancelOwnPendingAttack: TypedContractMethod<
      [targetTokenId: BigNumberish, attackIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    executeAttack: TypedContractMethod<
      [targetTokenId: BigNumberish, attackIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    farming: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getAttack: TypedContractMethod<
      [targetTokenId: BigNumberish, index: BigNumberish, ],
      [IPiratesV6.AttackDataStructOutput],
      'view'
    >
    

    
    getAttackCount: TypedContractMethod<
      [targetTokenId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getAttackTime: TypedContractMethod<
      [attackerTokenId: BigNumberish, targetTokenId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getPirateBoostExpiry: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getRemainingAttacksToday: TypedContractMethod<
      [attacker: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    hasPirateBoost: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    startAttack: TypedContractMethod<
      [attackerTokenId: BigNumberish, targetTokenId: BigNumberish, resourceId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'RESOURCE_COUNT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buyPirateBoost'): TypedContractMethod<
      [tokenId: BigNumberish, daysAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'canAttackTarget'): TypedContractMethod<
      [attacker: AddressLike, targetTokenId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'cancelOwnPendingAttack'): TypedContractMethod<
      [targetTokenId: BigNumberish, attackIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executeAttack'): TypedContractMethod<
      [targetTokenId: BigNumberish, attackIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'farming'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAttack'): TypedContractMethod<
      [targetTokenId: BigNumberish, index: BigNumberish, ],
      [IPiratesV6.AttackDataStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getAttackCount'): TypedContractMethod<
      [targetTokenId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAttackTime'): TypedContractMethod<
      [attackerTokenId: BigNumberish, targetTokenId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPirateBoostExpiry'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRemainingAttacksToday'): TypedContractMethod<
      [attacker: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hasPirateBoost'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'startAttack'): TypedContractMethod<
      [attackerTokenId: BigNumberish, targetTokenId: BigNumberish, resourceId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }