/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace CityBuildings {
      
    export type BuildingDefinitionStruct = {id: BigNumberish, name: string, allowedPlotType: BigNumberish, oilCost: BigNumberish, lemonsCost: BigNumberish, ironCost: BigNumberish, goldCost: BigNumberish, enabled: boolean}

    export type BuildingDefinitionStructOutput = [id: bigint, name: string, allowedPlotType: bigint, oilCost: bigint, lemonsCost: bigint, ironCost: bigint, goldCost: bigint, enabled: boolean] & {id: bigint, name: string, allowedPlotType: bigint, oilCost: bigint, lemonsCost: bigint, ironCost: bigint, goldCost: bigint, enabled: boolean }
  
    }

  export interface CommunityBuildingsInterface extends Interface {
    getFunction(nameOrSignature: "activateBuilding" | "buildingOfPlot" | "cityConfig" | "cityLand" | "cityRegistry" | "getBuildingDefinition" | "owner" | "planBuilding" | "renounceOwnership" | "setBuildingDefinition" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BuildingDefinitionSet" | "CommunityBuildingActivated" | "CommunityBuildingPlanned" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'activateBuilding', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'buildingOfPlot', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cityConfig', values?: undefined): string;
encodeFunctionData(functionFragment: 'cityLand', values?: undefined): string;
encodeFunctionData(functionFragment: 'cityRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBuildingDefinition', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'planBuilding', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setBuildingDefinition', values: [BigNumberish, string, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'activateBuilding', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buildingOfPlot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cityConfig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cityLand', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cityRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBuildingDefinition', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'planBuilding', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBuildingDefinition', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace BuildingDefinitionSetEvent {
      export type InputTuple = [buildingId: BigNumberish, name: string, allowedPlotType: BigNumberish, enabled: boolean];
      export type OutputTuple = [buildingId: bigint, name: string, allowedPlotType: bigint, enabled: boolean];
      export interface OutputObject {buildingId: bigint, name: string, allowedPlotType: bigint, enabled: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CommunityBuildingActivatedEvent {
      export type InputTuple = [plotId: BigNumberish];
      export type OutputTuple = [plotId: bigint];
      export interface OutputObject {plotId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CommunityBuildingPlannedEvent {
      export type InputTuple = [plotId: BigNumberish, buildingId: BigNumberish];
      export type OutputTuple = [plotId: bigint, buildingId: bigint];
      export interface OutputObject {plotId: bigint, buildingId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CommunityBuildings extends BaseContract {
    
    connect(runner?: ContractRunner | null): CommunityBuildings;
    waitForDeployment(): Promise<this>;

    interface: CommunityBuildingsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    activateBuilding: TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    buildingOfPlot: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, boolean, boolean] & {buildingId: bigint, exists: boolean, active: boolean }],
      'view'
    >
    

    
    cityConfig: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    cityLand: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    cityRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getBuildingDefinition: TypedContractMethod<
      [buildingId: BigNumberish, ],
      [CityBuildings.BuildingDefinitionStructOutput],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    planBuilding: TypedContractMethod<
      [plotId: BigNumberish, buildingId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setBuildingDefinition: TypedContractMethod<
      [buildingId: BigNumberish, name: string, allowedPlotType: BigNumberish, oilCost: BigNumberish, lemonsCost: BigNumberish, ironCost: BigNumberish, goldCost: BigNumberish, enabled: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'activateBuilding'): TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'buildingOfPlot'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, boolean, boolean] & {buildingId: bigint, exists: boolean, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'cityConfig'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cityLand'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cityRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getBuildingDefinition'): TypedContractMethod<
      [buildingId: BigNumberish, ],
      [CityBuildings.BuildingDefinitionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'planBuilding'): TypedContractMethod<
      [plotId: BigNumberish, buildingId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setBuildingDefinition'): TypedContractMethod<
      [buildingId: BigNumberish, name: string, allowedPlotType: BigNumberish, oilCost: BigNumberish, lemonsCost: BigNumberish, ironCost: BigNumberish, goldCost: BigNumberish, enabled: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BuildingDefinitionSet'): TypedContractEvent<BuildingDefinitionSetEvent.InputTuple, BuildingDefinitionSetEvent.OutputTuple, BuildingDefinitionSetEvent.OutputObject>;
getEvent(key: 'CommunityBuildingActivated'): TypedContractEvent<CommunityBuildingActivatedEvent.InputTuple, CommunityBuildingActivatedEvent.OutputTuple, CommunityBuildingActivatedEvent.OutputObject>;
getEvent(key: 'CommunityBuildingPlanned'): TypedContractEvent<CommunityBuildingPlannedEvent.InputTuple, CommunityBuildingPlannedEvent.OutputTuple, CommunityBuildingPlannedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'BuildingDefinitionSet(uint256,string,uint8,bool)': TypedContractEvent<BuildingDefinitionSetEvent.InputTuple, BuildingDefinitionSetEvent.OutputTuple, BuildingDefinitionSetEvent.OutputObject>;
      BuildingDefinitionSet: TypedContractEvent<BuildingDefinitionSetEvent.InputTuple, BuildingDefinitionSetEvent.OutputTuple, BuildingDefinitionSetEvent.OutputObject>;
    

      'CommunityBuildingActivated(uint256)': TypedContractEvent<CommunityBuildingActivatedEvent.InputTuple, CommunityBuildingActivatedEvent.OutputTuple, CommunityBuildingActivatedEvent.OutputObject>;
      CommunityBuildingActivated: TypedContractEvent<CommunityBuildingActivatedEvent.InputTuple, CommunityBuildingActivatedEvent.OutputTuple, CommunityBuildingActivatedEvent.OutputObject>;
    

      'CommunityBuildingPlanned(uint256,uint256)': TypedContractEvent<CommunityBuildingPlannedEvent.InputTuple, CommunityBuildingPlannedEvent.OutputTuple, CommunityBuildingPlannedEvent.OutputObject>;
      CommunityBuildingPlanned: TypedContractEvent<CommunityBuildingPlannedEvent.InputTuple, CommunityBuildingPlannedEvent.OutputTuple, CommunityBuildingPlannedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }