// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface PlotMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "PlotMath";
  readonly sourceName: "contracts/libraries/PlotMath.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220fb6e8e081a7dd44db4d53225047c2e713ff1fc89ffc61d4709a9018d9d1fb7c364736f6c63430008180033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220fb6e8e081a7dd44db4d53225047c2e713ff1fc89ffc61d4709a9018d9d1fb7c364736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/PlotMath.sol";
  readonly buildInfoId: "solc-0_8_24-276329d14ae1be4537cc6d289127051ca8ea930b";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["PlotMath"]: PlotMath$Type;
    ["contracts/libraries/PlotMath.sol:PlotMath"]: PlotMath$Type;
  }
}