// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ICityStatus$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ICityStatus";
  readonly sourceName: "contracts/interfaces/ICityStatus.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"plotId","type":"uint256"}],"name":"getDerivedStatus","outputs":[{"internalType":"enum CityTypes.PlotStatus","name":"","type":"uint8"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"plotId","type":"uint256"}],"name":"isLayerEligible","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"plotId","type":"uint256"}],"name":"recordMaintenance","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"plotId","type":"uint256"}],"name":"touchActivity","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ICityStatus.sol";
  readonly buildInfoId: "solc-0_8_24-276329d14ae1be4537cc6d289127051ca8ea930b";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ICityStatus"]: ICityStatus$Type;
    ["contracts/interfaces/ICityStatus.sol:ICityStatus"]: ICityStatus$Type;
  }
}