/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { CityErrors, CityErrorsInterface } from "../../libraries/CityErrors.js";

  const _abi = [
  {
    "inputs": [],
    "name": "InvalidConfig",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidFaction",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidPlotStatus",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidPlotType",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidValue",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MaxPersonalPlotsReached",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotAuthorized",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotPlotOwner",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PlotAlreadyExists",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PlotNotFound",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PlotSlotOccupied",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroAddress",
    "type": "error"
  }
] as const;

  const _bytecode = "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212202c544441175a91bb20e413b198eed6f24ad4f512d1e2a65ca64d7de1a8460d3764736f6c63430008180033";

  
      type CityErrorsConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: CityErrorsConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class CityErrors__factory extends ContractFactory {
    
      constructor(...args: CityErrorsConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<CityErrors & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): CityErrors__factory {
      return super.connect(runner) as CityErrors__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): CityErrorsInterface {
      return new Interface(_abi) as CityErrorsInterface;
    }
    
    override attach(address: string | Addressable): CityErrors {
      return super.attach(address) as CityErrors;
    }
  static connect(address: string, runner?: ContractRunner | null): CityErrors {
      return new Contract(address, _abi, runner) as unknown as CityErrors;
    }
  }

  
  