/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { CityEvents, CityEventsInterface } from "../../libraries/CityEvents.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "enum CityTypes.CommunityBuildingKind",
        "name": "buildingKind",
        "type": "uint8"
      }
    ],
    "name": "CommunityPlotReserved",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "admin",
        "type": "address"
      }
    ],
    "name": "ConfigInitialized",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "key",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "value",
        "type": "address"
      }
    ],
    "name": "CoreAddressSet",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint8",
        "name": "slotIndex",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "enum CityTypes.Faction",
        "name": "faction",
        "type": "uint8"
      }
    ],
    "name": "PersonalPlotReserved",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "oldOwner",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "PlotOwnerTransferred",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "enum CityTypes.PlotStatus",
        "name": "oldStatus",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "enum CityTypes.PlotStatus",
        "name": "newStatus",
        "type": "uint8"
      }
    ],
    "name": "PlotStatusUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "key",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      }
    ],
    "name": "UintConfigSet",
    "type": "event"
  }
] as const;

  const _bytecode = "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122087e04dc9998af94bf7c1bfb09aa4e42c61f765b0de1b124ad1c5a6bcd88848ad64736f6c63430008180033";

  
      type CityEventsConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: CityEventsConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class CityEvents__factory extends ContractFactory {
    
      constructor(...args: CityEventsConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<CityEvents & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): CityEvents__factory {
      return super.connect(runner) as CityEvents__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): CityEventsInterface {
      return new Interface(_abi) as CityEventsInterface;
    }
    
    override attach(address: string | Addressable): CityEvents {
      return super.attach(address) as CityEvents;
    }
  static connect(address: string, runner?: ContractRunner | null): CityEvents {
      return new Contract(address, _abi, runner) as unknown as CityEvents;
    }
  }

  
  