/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { CityEvents, CityEventsInterface } from "../../libraries/CityEvents.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint32",
        "name": "totalAetherUses",
        "type": "uint32"
      }
    ],
    "name": "AetherUseRecorded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "x",
        "type": "uint32"
      },
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "y",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "user",
        "type": "address"
      }
    ],
    "name": "AetherUsed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "CityKeyTokenSet",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "enum CityTypes.CommunityBuildingKind",
        "name": "buildingKind",
        "type": "uint8"
      }
    ],
    "name": "CommunityPlotReserved",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "admin",
        "type": "address"
      }
    ],
    "name": "ConfigInitialized",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "key",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "value",
        "type": "address"
      }
    ],
    "name": "CoreAddressSet",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "enum CityTypes.Faction",
        "name": "faction",
        "type": "uint8"
      }
    ],
    "name": "FactionChosen",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint32",
        "name": "newLayerCount",
        "type": "uint32"
      }
    ],
    "name": "LayerAdded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      }
    ],
    "name": "ManualStatusCleared",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint32",
        "name": "transferCount",
        "type": "uint32"
      }
    ],
    "name": "OwnershipTransferRecorded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint8",
        "name": "slotIndex",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "enum CityTypes.Faction",
        "name": "faction",
        "type": "uint8"
      }
    ],
    "name": "PersonalPlotReserved",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      }
    ],
    "name": "PlotCompleted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "firstBuilder",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "enum CityTypes.Faction",
        "name": "faction",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "genesisEra",
        "type": "bool"
      }
    ],
    "name": "PlotHistoryInitialized",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "oldOwner",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "PlotOwnerTransferred",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "enum CityTypes.PlotStatus",
        "name": "oldStatus",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "enum CityTypes.PlotStatus",
        "name": "newStatus",
        "type": "uint8"
      }
    ],
    "name": "PlotStatusUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "x",
        "type": "uint32"
      },
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "y",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "usedAether",
        "type": "bool"
      }
    ],
    "name": "QubiqCompleted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "x",
        "type": "uint32"
      },
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "y",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "contributor",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "oil",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "lemons",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "iron",
        "type": "uint256"
      }
    ],
    "name": "QubiqContributed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "key",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      }
    ],
    "name": "UintConfigSet",
    "type": "event"
  }
] as const;

  const _bytecode = "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220b015c80f668b7191d8aeb2d4a243a845ca20f45c5d5f9039dfdd3fabf65a9b2364736f6c63430008180033";

  
      type CityEventsConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: CityEventsConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class CityEvents__factory extends ContractFactory {
    
      constructor(...args: CityEventsConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<CityEvents & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): CityEvents__factory {
      return super.connect(runner) as CityEvents__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): CityEventsInterface {
      return new Interface(_abi) as CityEventsInterface;
    }
    
    override attach(address: string | Addressable): CityEvents {
      return super.attach(address) as CityEvents;
    }
  static connect(address: string, runner?: ContractRunner | null): CityEvents {
      return new Contract(address, _abi, runner) as unknown as CityEvents;
    }
  }

  
  