// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ICityEnchantmentItems$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ICityEnchantmentItems";
  readonly sourceName: "contracts/interfaces/ICityEnchantmentItems.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"from","type":"address"},{"internalType":"uint256","name":"itemId","type":"uint256"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"burnEnchantmentItem","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"itemId","type":"uint256"}],"name":"getEnchantmentItemMeta","outputs":[{"internalType":"uint256","name":"enchantmentDefinitionId","type":"uint256"},{"internalType":"uint256","name":"level","type":"uint256"},{"internalType":"uint256","name":"rarityTier","type":"uint256"},{"internalType":"bool","name":"burnOnUse","type":"bool"},{"internalType":"bool","name":"enabled","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"itemId","type":"uint256"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"mintEnchantmentItem","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ICityEnchantmentItems.sol";
  readonly buildInfoId: "solc-0_8_24-d939ecd63520850cc92f5ce840be21b4992d6f41";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ICityEnchantmentItems"]: ICityEnchantmentItems$Type;
    ["contracts/interfaces/ICityEnchantmentItems.sol:ICityEnchantmentItems"]: ICityEnchantmentItems$Type;
  }
}