/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface CityStatusInterface extends Interface {
    getFunction(nameOrSignature: "authorizedCallers" | "cityConfig" | "cityRegistry" | "clearManualStatus" | "getDerivedStatus" | "isLayerEligible" | "lastActivityAtOf" | "lastMaintenanceAtOf" | "manualStatusOverrideOf" | "owner" | "recordMaintenance" | "renounceOwnership" | "setAuthorizedCaller" | "setManualStatus" | "touchActivity" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ManualStatusCleared" | "OwnershipTransferred" | "PlotStatusUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'authorizedCallers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'cityConfig', values?: undefined): string;
encodeFunctionData(functionFragment: 'cityRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'clearManualStatus', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getDerivedStatus', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isLayerEligible', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'lastActivityAtOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'lastMaintenanceAtOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'manualStatusOverrideOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordMaintenance', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAuthorizedCaller', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setManualStatus', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'touchActivity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'authorizedCallers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cityConfig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cityRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'clearManualStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDerivedStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isLayerEligible', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastActivityAtOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastMaintenanceAtOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'manualStatusOverrideOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordMaintenance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAuthorizedCaller', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setManualStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'touchActivity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace ManualStatusClearedEvent {
      export type InputTuple = [plotId: BigNumberish];
      export type OutputTuple = [plotId: bigint];
      export interface OutputObject {plotId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlotStatusUpdatedEvent {
      export type InputTuple = [plotId: BigNumberish, oldStatus: BigNumberish, newStatus: BigNumberish];
      export type OutputTuple = [plotId: bigint, oldStatus: bigint, newStatus: bigint];
      export interface OutputObject {plotId: bigint, oldStatus: bigint, newStatus: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CityStatus extends BaseContract {
    
    connect(runner?: ContractRunner | null): CityStatus;
    waitForDeployment(): Promise<this>;

    interface: CityStatusInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    authorizedCallers: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    cityConfig: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    cityRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    clearManualStatus: TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getDerivedStatus: TypedContractMethod<
      [plotId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    isLayerEligible: TypedContractMethod<
      [plotId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    lastActivityAtOf: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    lastMaintenanceAtOf: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    manualStatusOverrideOf: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    recordMaintenance: TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setAuthorizedCaller: TypedContractMethod<
      [caller: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setManualStatus: TypedContractMethod<
      [plotId: BigNumberish, status: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    touchActivity: TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'authorizedCallers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'cityConfig'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cityRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'clearManualStatus'): TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getDerivedStatus'): TypedContractMethod<
      [plotId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isLayerEligible'): TypedContractMethod<
      [plotId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lastActivityAtOf'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lastMaintenanceAtOf'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'manualStatusOverrideOf'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recordMaintenance'): TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAuthorizedCaller'): TypedContractMethod<
      [caller: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setManualStatus'): TypedContractMethod<
      [plotId: BigNumberish, status: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'touchActivity'): TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ManualStatusCleared'): TypedContractEvent<ManualStatusClearedEvent.InputTuple, ManualStatusClearedEvent.OutputTuple, ManualStatusClearedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PlotStatusUpdated'): TypedContractEvent<PlotStatusUpdatedEvent.InputTuple, PlotStatusUpdatedEvent.OutputTuple, PlotStatusUpdatedEvent.OutputObject>;

    filters: {
      
      'ManualStatusCleared(uint256)': TypedContractEvent<ManualStatusClearedEvent.InputTuple, ManualStatusClearedEvent.OutputTuple, ManualStatusClearedEvent.OutputObject>;
      ManualStatusCleared: TypedContractEvent<ManualStatusClearedEvent.InputTuple, ManualStatusClearedEvent.OutputTuple, ManualStatusClearedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PlotStatusUpdated(uint256,uint8,uint8)': TypedContractEvent<PlotStatusUpdatedEvent.InputTuple, PlotStatusUpdatedEvent.OutputTuple, PlotStatusUpdatedEvent.OutputObject>;
      PlotStatusUpdated: TypedContractEvent<PlotStatusUpdatedEvent.InputTuple, PlotStatusUpdatedEvent.OutputTuple, PlotStatusUpdatedEvent.OutputObject>;
    
    };
  }