/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface CityHistoryInterface extends Interface {
    getFunction(nameOrSignature: "cityRegistry" | "initializePlotHistory" | "owner" | "provenanceOf" | "recordAetherUse" | "recordLayerAdded" | "recordOwnershipTransfer" | "renounceOwnership" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'cityRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'initializePlotHistory', values: [BigNumberish, AddressLike, BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'provenanceOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordAetherUse', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordLayerAdded', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordOwnershipTransfer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'cityRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initializePlotHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'provenanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordAetherUse', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordLayerAdded', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordOwnershipTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CityHistory extends BaseContract {
    
    connect(runner?: ContractRunner | null): CityHistory;
    waitForDeployment(): Promise<this>;

    interface: CityHistoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    cityRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    initializePlotHistory: TypedContractMethod<
      [plotId: BigNumberish, firstBuilder: AddressLike, faction: BigNumberish, genesisEra: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    provenanceOf: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {firstBuilder: string, createdAt: bigint, layerCount: bigint, ownershipTransfers: bigint, aetherUses: bigint, historicScore: bigint, originFaction: bigint, genesisEra: boolean }],
      'view'
    >
    

    
    recordAetherUse: TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordLayerAdded: TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordOwnershipTransfer: TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'cityRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'initializePlotHistory'): TypedContractMethod<
      [plotId: BigNumberish, firstBuilder: AddressLike, faction: BigNumberish, genesisEra: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'provenanceOf'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {firstBuilder: string, createdAt: bigint, layerCount: bigint, ownershipTransfers: bigint, aetherUses: bigint, historicScore: bigint, originFaction: bigint, genesisEra: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'recordAetherUse'): TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordLayerAdded'): TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordOwnershipTransfer'): TypedContractMethod<
      [plotId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }