/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener } from "../common.js"
  

  export interface CityEventsInterface extends Interface {
    

    getEvent(nameOrSignatureOrTopic: "CommunityPlotReserved" | "ConfigInitialized" | "CoreAddressSet" | "PersonalPlotReserved" | "PlotOwnerTransferred" | "PlotStatusUpdated" | "UintConfigSet"): EventFragment;

    

    
  }

  
    export namespace CommunityPlotReservedEvent {
      export type InputTuple = [plotId: BigNumberish, buildingKind: BigNumberish];
      export type OutputTuple = [plotId: bigint, buildingKind: bigint];
      export interface OutputObject {plotId: bigint, buildingKind: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ConfigInitializedEvent {
      export type InputTuple = [admin: AddressLike];
      export type OutputTuple = [admin: string];
      export interface OutputObject {admin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CoreAddressSetEvent {
      export type InputTuple = [key: BytesLike, value: AddressLike];
      export type OutputTuple = [key: string, value: string];
      export interface OutputObject {key: string, value: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PersonalPlotReservedEvent {
      export type InputTuple = [owner: AddressLike, plotId: BigNumberish, slotIndex: BigNumberish, faction: BigNumberish];
      export type OutputTuple = [owner: string, plotId: bigint, slotIndex: bigint, faction: bigint];
      export interface OutputObject {owner: string, plotId: bigint, slotIndex: bigint, faction: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlotOwnerTransferredEvent {
      export type InputTuple = [plotId: BigNumberish, oldOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [plotId: bigint, oldOwner: string, newOwner: string];
      export interface OutputObject {plotId: bigint, oldOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlotStatusUpdatedEvent {
      export type InputTuple = [plotId: BigNumberish, oldStatus: BigNumberish, newStatus: BigNumberish];
      export type OutputTuple = [plotId: bigint, oldStatus: bigint, newStatus: bigint];
      export interface OutputObject {plotId: bigint, oldStatus: bigint, newStatus: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UintConfigSetEvent {
      export type InputTuple = [key: BytesLike, value: BigNumberish];
      export type OutputTuple = [key: string, value: bigint];
      export interface OutputObject {key: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CityEvents extends BaseContract {
    
    connect(runner?: ContractRunner | null): CityEvents;
    waitForDeployment(): Promise<this>;

    interface: CityEventsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    

    getEvent(key: 'CommunityPlotReserved'): TypedContractEvent<CommunityPlotReservedEvent.InputTuple, CommunityPlotReservedEvent.OutputTuple, CommunityPlotReservedEvent.OutputObject>;
getEvent(key: 'ConfigInitialized'): TypedContractEvent<ConfigInitializedEvent.InputTuple, ConfigInitializedEvent.OutputTuple, ConfigInitializedEvent.OutputObject>;
getEvent(key: 'CoreAddressSet'): TypedContractEvent<CoreAddressSetEvent.InputTuple, CoreAddressSetEvent.OutputTuple, CoreAddressSetEvent.OutputObject>;
getEvent(key: 'PersonalPlotReserved'): TypedContractEvent<PersonalPlotReservedEvent.InputTuple, PersonalPlotReservedEvent.OutputTuple, PersonalPlotReservedEvent.OutputObject>;
getEvent(key: 'PlotOwnerTransferred'): TypedContractEvent<PlotOwnerTransferredEvent.InputTuple, PlotOwnerTransferredEvent.OutputTuple, PlotOwnerTransferredEvent.OutputObject>;
getEvent(key: 'PlotStatusUpdated'): TypedContractEvent<PlotStatusUpdatedEvent.InputTuple, PlotStatusUpdatedEvent.OutputTuple, PlotStatusUpdatedEvent.OutputObject>;
getEvent(key: 'UintConfigSet'): TypedContractEvent<UintConfigSetEvent.InputTuple, UintConfigSetEvent.OutputTuple, UintConfigSetEvent.OutputObject>;

    filters: {
      
      'CommunityPlotReserved(uint256,uint8)': TypedContractEvent<CommunityPlotReservedEvent.InputTuple, CommunityPlotReservedEvent.OutputTuple, CommunityPlotReservedEvent.OutputObject>;
      CommunityPlotReserved: TypedContractEvent<CommunityPlotReservedEvent.InputTuple, CommunityPlotReservedEvent.OutputTuple, CommunityPlotReservedEvent.OutputObject>;
    

      'ConfigInitialized(address)': TypedContractEvent<ConfigInitializedEvent.InputTuple, ConfigInitializedEvent.OutputTuple, ConfigInitializedEvent.OutputObject>;
      ConfigInitialized: TypedContractEvent<ConfigInitializedEvent.InputTuple, ConfigInitializedEvent.OutputTuple, ConfigInitializedEvent.OutputObject>;
    

      'CoreAddressSet(bytes32,address)': TypedContractEvent<CoreAddressSetEvent.InputTuple, CoreAddressSetEvent.OutputTuple, CoreAddressSetEvent.OutputObject>;
      CoreAddressSet: TypedContractEvent<CoreAddressSetEvent.InputTuple, CoreAddressSetEvent.OutputTuple, CoreAddressSetEvent.OutputObject>;
    

      'PersonalPlotReserved(address,uint256,uint8,uint8)': TypedContractEvent<PersonalPlotReservedEvent.InputTuple, PersonalPlotReservedEvent.OutputTuple, PersonalPlotReservedEvent.OutputObject>;
      PersonalPlotReserved: TypedContractEvent<PersonalPlotReservedEvent.InputTuple, PersonalPlotReservedEvent.OutputTuple, PersonalPlotReservedEvent.OutputObject>;
    

      'PlotOwnerTransferred(uint256,address,address)': TypedContractEvent<PlotOwnerTransferredEvent.InputTuple, PlotOwnerTransferredEvent.OutputTuple, PlotOwnerTransferredEvent.OutputObject>;
      PlotOwnerTransferred: TypedContractEvent<PlotOwnerTransferredEvent.InputTuple, PlotOwnerTransferredEvent.OutputTuple, PlotOwnerTransferredEvent.OutputObject>;
    

      'PlotStatusUpdated(uint256,uint8,uint8)': TypedContractEvent<PlotStatusUpdatedEvent.InputTuple, PlotStatusUpdatedEvent.OutputTuple, PlotStatusUpdatedEvent.OutputObject>;
      PlotStatusUpdated: TypedContractEvent<PlotStatusUpdatedEvent.InputTuple, PlotStatusUpdatedEvent.OutputTuple, PlotStatusUpdatedEvent.OutputObject>;
    

      'UintConfigSet(bytes32,uint256)': TypedContractEvent<UintConfigSetEvent.InputTuple, UintConfigSetEvent.OutputTuple, UintConfigSetEvent.OutputObject>;
      UintConfigSet: TypedContractEvent<UintConfigSetEvent.InputTuple, UintConfigSetEvent.OutputTuple, UintConfigSetEvent.OutputObject>;
    
    };
  }