/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as districtLogicSol from './DistrictLogic.sol/index.js';
export type { districtLogicSol };
export type { CityErrors } from './CityErrors.js';
export type { CityEvents } from './CityEvents.js';