/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ICityStatus, ICityStatusInterface } from "../../interfaces/ICityStatus.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      }
    ],
    "name": "getDerivedStatus",
    "outputs": [
      {
        "internalType": "enum CityTypes.PlotStatus",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      }
    ],
    "name": "isLayerEligible",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      }
    ],
    "name": "recordMaintenance",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "plotId",
        "type": "uint256"
      }
    ],
    "name": "touchActivity",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class ICityStatus__factory {
    static readonly abi = _abi;
    static createInterface(): ICityStatusInterface {
      return new Interface(_abi) as ICityStatusInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ICityStatus {
      return new Contract(address, _abi, runner) as unknown as ICityStatus;
    }
  }
  