/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ICityBlueprints, ICityBlueprintsInterface } from "../../interfaces/ICityBlueprints.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "blueprintId",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "mintBlueprint",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class ICityBlueprints__factory {
    static readonly abi = _abi;
    static createInterface(): ICityBlueprintsInterface {
      return new Interface(_abi) as ICityBlueprintsInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ICityBlueprints {
      return new Contract(address, _abi, runner) as unknown as ICityBlueprints;
    }
  }
  