/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IMercenaryV4, IMercenaryV4Interface } from "../../interfaces/IMercenaryV4.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "slotIndex",
        "type": "uint8"
      },
      {
        "internalType": "uint256",
        "name": "newTokenId",
        "type": "uint256"
      }
    ],
    "name": "emergencyMoveProtection",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      }
    ],
    "name": "getDefenderProfile",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "points",
        "type": "uint256"
      },
      {
        "internalType": "uint8",
        "name": "rank",
        "type": "uint8"
      },
      {
        "internalType": "uint256",
        "name": "discountBps",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "protectedDays",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "defenses",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "extensionsCount",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "cleanups",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "title",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "getProtectionData",
    "outputs": [
      {
        "internalType": "address",
        "name": "protector",
        "type": "address"
      },
      {
        "internalType": "uint8",
        "name": "slotIndex",
        "type": "uint8"
      },
      {
        "internalType": "bool",
        "name": "active",
        "type": "bool"
      },
      {
        "internalType": "uint256",
        "name": "startTime",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "expiry",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "cooldownUntil",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "emergencyReadyAt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "tier",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "protectionPercent",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "getProtectionLevel",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      }
    ],
    "name": "getRank",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "rank",
        "type": "uint8"
      },
      {
        "internalType": "string",
        "name": "name",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      }
    ],
    "name": "getWalletSlots",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "slots",
        "type": "uint8"
      },
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "tokenId",
            "type": "uint256"
          },
          {
            "internalType": "uint64",
            "name": "startTime",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "expiry",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "cooldownUntil",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "emergencyReadyAt",
            "type": "uint64"
          },
          {
            "internalType": "uint8",
            "name": "protectionTier",
            "type": "uint8"
          },
          {
            "internalType": "bool",
            "name": "active",
            "type": "bool"
          }
        ],
        "internalType": "struct IMercenaryV4.ProtectionSlot[3]",
        "name": "data",
        "type": "tuple[3]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "slotIndex",
        "type": "uint8"
      },
      {
        "internalType": "uint256",
        "name": "newTokenId",
        "type": "uint256"
      }
    ],
    "name": "moveProtection",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IMercenaryV4__factory {
    static readonly abi = _abi;
    static createInterface(): IMercenaryV4Interface {
      return new Interface(_abi) as IMercenaryV4Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): IMercenaryV4 {
      return new Contract(address, _abi, runner) as unknown as IMercenaryV4;
    }
  }
  