/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFarmingV6__factory } from './IFarmingV6__factory.js';
export { IINPI__factory } from './IINPI__factory.js';
export { IInpinityNFT__factory } from './IInpinityNFT__factory.js';
export { IMercenaryV4__factory } from './IMercenaryV4__factory.js';
export { IPIT__factory } from './IPIT__factory.js';
export { IPartnershipV2__factory } from './IPartnershipV2__factory.js';
export { IPiratesV6__factory } from './IPiratesV6__factory.js';
export { IResourceToken__factory } from './IResourceToken__factory.js';