/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IPartnershipV2, IPartnershipV2Interface } from "../../interfaces/IPartnershipV2.js";

  const _abi = [
  {
    "inputs": [],
    "name": "farming",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "partnerId",
        "type": "uint256"
      }
    ],
    "name": "getPartnerBlock",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "inpinityNFT",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "isPartnerBlock",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IPartnershipV2__factory {
    static readonly abi = _abi;
    static createInterface(): IPartnershipV2Interface {
      return new Interface(_abi) as IPartnershipV2Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): IPartnershipV2 {
      return new Contract(address, _abi, runner) as unknown as IPartnershipV2;
    }
  }
  