// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface BonusTypes$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "BonusTypes";
  readonly sourceName: "contracts/crafting/BonusTypes.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220f39e374ca251bb78b50352371be52a018e973099a60e0e5ee065a442b23f02ea64736f6c63430008180033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220f39e374ca251bb78b50352371be52a018e973099a60e0e5ee065a442b23f02ea64736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/crafting/BonusTypes.sol";
  readonly buildInfoId: "solc-0_8_24-49f309ca72e110257b80b48521f83f19d6d8b625";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["BonusTypes"]: BonusTypes$Type;
    ["contracts/crafting/BonusTypes.sol:BonusTypes"]: BonusTypes$Type;
  }
}