// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface CityErrors$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "CityErrors";
  readonly sourceName: "contracts/libraries/CityErrors.sol";
  readonly abi: [{"inputs":[],"name":"InvalidConfig","type":"error"},{"inputs":[],"name":"InvalidFaction","type":"error"},{"inputs":[],"name":"InvalidPlotStatus","type":"error"},{"inputs":[],"name":"InvalidPlotType","type":"error"},{"inputs":[],"name":"InvalidValue","type":"error"},{"inputs":[],"name":"MaxPersonalPlotsReached","type":"error"},{"inputs":[],"name":"NotAuthorized","type":"error"},{"inputs":[],"name":"NotPlotOwner","type":"error"},{"inputs":[],"name":"PlotAlreadyExists","type":"error"},{"inputs":[],"name":"PlotNotFound","type":"error"},{"inputs":[],"name":"PlotSlotOccupied","type":"error"},{"inputs":[],"name":"ZeroAddress","type":"error"}];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220921360f3ccea40707e8d15baa77ca0a5062394cd88583a16811e86c0c7b4750164736f6c63430008180033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220921360f3ccea40707e8d15baa77ca0a5062394cd88583a16811e86c0c7b4750164736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/CityErrors.sol";
  readonly buildInfoId: "solc-0_8_24-276329d14ae1be4537cc6d289127051ca8ea930b";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["CityErrors"]: CityErrors$Type;
    ["contracts/libraries/CityErrors.sol:CityErrors"]: CityErrors$Type;
  }
}