// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface QubiqMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "QubiqMath";
  readonly sourceName: "contracts/libraries/QubiqMath.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea264697066735822122071d3274a5d4f0b3d758da24c219eedf63d19865cfd1fb2b758ad33a5fe66f6c664736f6c63430008180033";
  readonly deployedBytecode: "0x5f80fdfea264697066735822122071d3274a5d4f0b3d758da24c219eedf63d19865cfd1fb2b758ad33a5fe66f6c664736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/QubiqMath.sol";
  readonly buildInfoId: "solc-0_8_24-276329d14ae1be4537cc6d289127051ca8ea930b";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["QubiqMath"]: QubiqMath$Type;
    ["contracts/libraries/QubiqMath.sol:QubiqMath"]: QubiqMath$Type;
  }
}