/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace BonusTypes {
      
    export type BonusSetStruct = {minDamageBonus: BigNumberish, maxDamageBonus: BigNumberish, attackSpeedBonus: BigNumberish, critChanceBpsBonus: BigNumberish, critMultiplierBpsBonus: BigNumberish, accuracyBpsBonus: BigNumberish, rangeBonus: BigNumberish, maxDurabilityBonus: BigNumberish, armorPenBpsBonus: BigNumberish, blockChanceBpsBonus: BigNumberish, lifeStealBpsBonus: BigNumberish, energyCostBonus: BigNumberish, heatGenerationBonus: BigNumberish, stabilityBonus: BigNumberish, cooldownMsBonus: BigNumberish, projectileSpeedBonus: BigNumberish, aoeRadiusBonus: BigNumberish, enchantmentSlotsBonus: BigNumberish, materiaSlotsBonus: BigNumberish}

    export type BonusSetStructOutput = [minDamageBonus: bigint, maxDamageBonus: bigint, attackSpeedBonus: bigint, critChanceBpsBonus: bigint, critMultiplierBpsBonus: bigint, accuracyBpsBonus: bigint, rangeBonus: bigint, maxDurabilityBonus: bigint, armorPenBpsBonus: bigint, blockChanceBpsBonus: bigint, lifeStealBpsBonus: bigint, energyCostBonus: bigint, heatGenerationBonus: bigint, stabilityBonus: bigint, cooldownMsBonus: bigint, projectileSpeedBonus: bigint, aoeRadiusBonus: bigint, enchantmentSlotsBonus: bigint, materiaSlotsBonus: bigint] & {minDamageBonus: bigint, maxDamageBonus: bigint, attackSpeedBonus: bigint, critChanceBpsBonus: bigint, critMultiplierBpsBonus: bigint, accuracyBpsBonus: bigint, rangeBonus: bigint, maxDurabilityBonus: bigint, armorPenBpsBonus: bigint, blockChanceBpsBonus: bigint, lifeStealBpsBonus: bigint, energyCostBonus: bigint, heatGenerationBonus: bigint, stabilityBonus: bigint, cooldownMsBonus: bigint, projectileSpeedBonus: bigint, aoeRadiusBonus: bigint, enchantmentSlotsBonus: bigint, materiaSlotsBonus: bigint }
  
    }

export declare namespace CityMateria {
      
    export type MateriaDefinitionStruct = {id: BigNumberish, name: string, category: BigNumberish, element: BigNumberish, rarityTier: BigNumberish, maxLevel: BigNumberish, enabled: boolean}

    export type MateriaDefinitionStructOutput = [id: bigint, name: string, category: bigint, element: bigint, rarityTier: bigint, maxLevel: bigint, enabled: boolean] & {id: bigint, name: string, category: bigint, element: bigint, rarityTier: bigint, maxLevel: bigint, enabled: boolean }
  
    }

  export interface CityMateriaInterface extends Interface {
    getFunction(nameOrSignature: "authorizedCallers" | "getMateriaBonuses" | "getMateriaDefinition" | "getMateriaMeta" | "hasBonusesForLevel" | "isMateriaEnabled" | "isMateriaUsable" | "materiaBonusesOf" | "materiaDefinitionOf" | "materiaExists" | "owner" | "renounceOwnership" | "setAuthorizedCaller" | "setMateriaBonuses" | "setMateriaDefinition" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuthorizedCallerSet" | "MateriaBonusesSet" | "MateriaDefinitionSet" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'authorizedCallers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getMateriaBonuses', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMateriaDefinition', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMateriaMeta', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasBonusesForLevel', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'isMateriaEnabled', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isMateriaUsable', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'materiaBonusesOf', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'materiaDefinitionOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'materiaExists', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAuthorizedCaller', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setMateriaBonuses', values: [BigNumberish, BigNumberish, BonusTypes.BonusSetStruct]): string;
encodeFunctionData(functionFragment: 'setMateriaDefinition', values: [BigNumberish, string, BigNumberish, BigNumberish, BigNumberish, BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'authorizedCallers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMateriaBonuses', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMateriaDefinition', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMateriaMeta', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasBonusesForLevel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isMateriaEnabled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isMateriaUsable', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'materiaBonusesOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'materiaDefinitionOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'materiaExists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAuthorizedCaller', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMateriaBonuses', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMateriaDefinition', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace AuthorizedCallerSetEvent {
      export type InputTuple = [caller: AddressLike, allowed: boolean];
      export type OutputTuple = [caller: string, allowed: boolean];
      export interface OutputObject {caller: string, allowed: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MateriaBonusesSetEvent {
      export type InputTuple = [materiaId: BigNumberish, level: BigNumberish];
      export type OutputTuple = [materiaId: bigint, level: bigint];
      export interface OutputObject {materiaId: bigint, level: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MateriaDefinitionSetEvent {
      export type InputTuple = [materiaId: BigNumberish, name: string, category: BigNumberish, element: BigNumberish, rarityTier: BigNumberish, maxLevel: BigNumberish, enabled: boolean];
      export type OutputTuple = [materiaId: bigint, name: string, category: bigint, element: bigint, rarityTier: bigint, maxLevel: bigint, enabled: boolean];
      export interface OutputObject {materiaId: bigint, name: string, category: bigint, element: bigint, rarityTier: bigint, maxLevel: bigint, enabled: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CityMateria extends BaseContract {
    
    connect(runner?: ContractRunner | null): CityMateria;
    waitForDeployment(): Promise<this>;

    interface: CityMateriaInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    authorizedCallers: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    getMateriaBonuses: TypedContractMethod<
      [materiaId: BigNumberish, level: BigNumberish, ],
      [BonusTypes.BonusSetStructOutput],
      'view'
    >
    

    
    getMateriaDefinition: TypedContractMethod<
      [materiaId: BigNumberish, ],
      [CityMateria.MateriaDefinitionStructOutput],
      'view'
    >
    

    
    getMateriaMeta: TypedContractMethod<
      [materiaId: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, boolean] & {name: string, category: bigint, element: bigint, rarityTier: bigint, maxLevel: bigint, enabled: boolean }],
      'view'
    >
    

    
    hasBonusesForLevel: TypedContractMethod<
      [materiaId: BigNumberish, level: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    isMateriaEnabled: TypedContractMethod<
      [materiaId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    isMateriaUsable: TypedContractMethod<
      [materiaId: BigNumberish, level: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    materiaBonusesOf: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {minDamageBonus: bigint, maxDamageBonus: bigint, attackSpeedBonus: bigint, critChanceBpsBonus: bigint, critMultiplierBpsBonus: bigint, accuracyBpsBonus: bigint, rangeBonus: bigint, maxDurabilityBonus: bigint, armorPenBpsBonus: bigint, blockChanceBpsBonus: bigint, lifeStealBpsBonus: bigint, energyCostBonus: bigint, heatGenerationBonus: bigint, stabilityBonus: bigint, cooldownMsBonus: bigint, projectileSpeedBonus: bigint, aoeRadiusBonus: bigint, enchantmentSlotsBonus: bigint, materiaSlotsBonus: bigint }],
      'view'
    >
    

    
    materiaDefinitionOf: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, bigint, bigint, boolean] & {id: bigint, name: string, category: bigint, element: bigint, rarityTier: bigint, maxLevel: bigint, enabled: boolean }],
      'view'
    >
    

    
    materiaExists: TypedContractMethod<
      [materiaId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setAuthorizedCaller: TypedContractMethod<
      [caller: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setMateriaBonuses: TypedContractMethod<
      [materiaId: BigNumberish, level: BigNumberish, bonuses: BonusTypes.BonusSetStruct, ],
      [void],
      'nonpayable'
    >
    

    
    setMateriaDefinition: TypedContractMethod<
      [materiaId: BigNumberish, name: string, category: BigNumberish, element: BigNumberish, rarityTier: BigNumberish, maxLevel: BigNumberish, enabled: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'authorizedCallers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getMateriaBonuses'): TypedContractMethod<
      [materiaId: BigNumberish, level: BigNumberish, ],
      [BonusTypes.BonusSetStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getMateriaDefinition'): TypedContractMethod<
      [materiaId: BigNumberish, ],
      [CityMateria.MateriaDefinitionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getMateriaMeta'): TypedContractMethod<
      [materiaId: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, boolean] & {name: string, category: bigint, element: bigint, rarityTier: bigint, maxLevel: bigint, enabled: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'hasBonusesForLevel'): TypedContractMethod<
      [materiaId: BigNumberish, level: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isMateriaEnabled'): TypedContractMethod<
      [materiaId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isMateriaUsable'): TypedContractMethod<
      [materiaId: BigNumberish, level: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'materiaBonusesOf'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {minDamageBonus: bigint, maxDamageBonus: bigint, attackSpeedBonus: bigint, critChanceBpsBonus: bigint, critMultiplierBpsBonus: bigint, accuracyBpsBonus: bigint, rangeBonus: bigint, maxDurabilityBonus: bigint, armorPenBpsBonus: bigint, blockChanceBpsBonus: bigint, lifeStealBpsBonus: bigint, energyCostBonus: bigint, heatGenerationBonus: bigint, stabilityBonus: bigint, cooldownMsBonus: bigint, projectileSpeedBonus: bigint, aoeRadiusBonus: bigint, enchantmentSlotsBonus: bigint, materiaSlotsBonus: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'materiaDefinitionOf'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, bigint, bigint, boolean] & {id: bigint, name: string, category: bigint, element: bigint, rarityTier: bigint, maxLevel: bigint, enabled: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'materiaExists'): TypedContractMethod<
      [materiaId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAuthorizedCaller'): TypedContractMethod<
      [caller: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMateriaBonuses'): TypedContractMethod<
      [materiaId: BigNumberish, level: BigNumberish, bonuses: BonusTypes.BonusSetStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMateriaDefinition'): TypedContractMethod<
      [materiaId: BigNumberish, name: string, category: BigNumberish, element: BigNumberish, rarityTier: BigNumberish, maxLevel: BigNumberish, enabled: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AuthorizedCallerSet'): TypedContractEvent<AuthorizedCallerSetEvent.InputTuple, AuthorizedCallerSetEvent.OutputTuple, AuthorizedCallerSetEvent.OutputObject>;
getEvent(key: 'MateriaBonusesSet'): TypedContractEvent<MateriaBonusesSetEvent.InputTuple, MateriaBonusesSetEvent.OutputTuple, MateriaBonusesSetEvent.OutputObject>;
getEvent(key: 'MateriaDefinitionSet'): TypedContractEvent<MateriaDefinitionSetEvent.InputTuple, MateriaDefinitionSetEvent.OutputTuple, MateriaDefinitionSetEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'AuthorizedCallerSet(address,bool)': TypedContractEvent<AuthorizedCallerSetEvent.InputTuple, AuthorizedCallerSetEvent.OutputTuple, AuthorizedCallerSetEvent.OutputObject>;
      AuthorizedCallerSet: TypedContractEvent<AuthorizedCallerSetEvent.InputTuple, AuthorizedCallerSetEvent.OutputTuple, AuthorizedCallerSetEvent.OutputObject>;
    

      'MateriaBonusesSet(uint256,uint256)': TypedContractEvent<MateriaBonusesSetEvent.InputTuple, MateriaBonusesSetEvent.OutputTuple, MateriaBonusesSetEvent.OutputObject>;
      MateriaBonusesSet: TypedContractEvent<MateriaBonusesSetEvent.InputTuple, MateriaBonusesSetEvent.OutputTuple, MateriaBonusesSetEvent.OutputObject>;
    

      'MateriaDefinitionSet(uint256,string,uint8,uint8,uint256,uint256,bool)': TypedContractEvent<MateriaDefinitionSetEvent.InputTuple, MateriaDefinitionSetEvent.OutputTuple, MateriaDefinitionSetEvent.OutputObject>;
      MateriaDefinitionSet: TypedContractEvent<MateriaDefinitionSetEvent.InputTuple, MateriaDefinitionSetEvent.OutputTuple, MateriaDefinitionSetEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }