// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface CityRoles$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "CityRoles";
  readonly sourceName: "contracts/access/CityRoles.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220d1eca6316c70273fce43579ee05a05eb770c1e0b3991fcdd41fd490773370dc164736f6c63430008180033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220d1eca6316c70273fce43579ee05a05eb770c1e0b3991fcdd41fd490773370dc164736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/access/CityRoles.sol";
  readonly buildInfoId: "solc-0_8_24-276329d14ae1be4537cc6d289127051ca8ea930b";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["CityRoles"]: CityRoles$Type;
    ["contracts/access/CityRoles.sol:CityRoles"]: CityRoles$Type;
  }
}