// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ICityWeaponSockets$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ICityWeaponSockets";
  readonly sourceName: "contracts/interfaces/ICityWeaponSockets.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"getTotalBonuses","outputs":[{"components":[{"internalType":"int256","name":"minDamageBonus","type":"int256"},{"internalType":"int256","name":"maxDamageBonus","type":"int256"},{"internalType":"int256","name":"attackSpeedBonus","type":"int256"},{"internalType":"int256","name":"critChanceBpsBonus","type":"int256"},{"internalType":"int256","name":"critMultiplierBpsBonus","type":"int256"},{"internalType":"int256","name":"accuracyBpsBonus","type":"int256"},{"internalType":"int256","name":"rangeBonus","type":"int256"},{"internalType":"int256","name":"maxDurabilityBonus","type":"int256"},{"internalType":"int256","name":"armorPenBpsBonus","type":"int256"},{"internalType":"int256","name":"blockChanceBpsBonus","type":"int256"},{"internalType":"int256","name":"lifeStealBpsBonus","type":"int256"},{"internalType":"int256","name":"energyCostBonus","type":"int256"},{"internalType":"int256","name":"heatGenerationBonus","type":"int256"},{"internalType":"int256","name":"stabilityBonus","type":"int256"},{"internalType":"int256","name":"cooldownMsBonus","type":"int256"},{"internalType":"int256","name":"projectileSpeedBonus","type":"int256"},{"internalType":"int256","name":"aoeRadiusBonus","type":"int256"},{"internalType":"int256","name":"enchantmentSlotsBonus","type":"int256"},{"internalType":"int256","name":"materiaSlotsBonus","type":"int256"}],"internalType":"struct ICityWeaponSockets.TotalBonuses","name":"","type":"tuple"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ICityWeaponSockets.sol";
  readonly buildInfoId: "solc-0_8_24-535551d58c37853673c9d8b9b9df580f8a71fee3";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ICityWeaponSockets"]: ICityWeaponSockets$Type;
    ["contracts/interfaces/ICityWeaponSockets.sol:ICityWeaponSockets"]: ICityWeaponSockets$Type;
  }
}