// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IInpinityNFT$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IInpinityNFT";
  readonly sourceName: "contracts/interfaces/IInpinityNFT.sol";
  readonly abi: [{"inputs":[],"name":"MAX_ROWS","outputs":[{"internalType":"uint16","name":"","type":"uint16"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"currentMaxRow","outputs":[{"internalType":"uint16","name":"","type":"uint16"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"getBlockPosition","outputs":[{"internalType":"uint16","name":"row","type":"uint16"},{"internalType":"uint16","name":"col","type":"uint16"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"ownerOf","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IInpinityNFT.sol";
  readonly buildInfoId: "solc-0_8_24-276329d14ae1be4537cc6d289127051ca8ea930b";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IInpinityNFT"]: IInpinityNFT$Type;
    ["contracts/interfaces/IInpinityNFT.sol:IInpinityNFT"]: IInpinityNFT$Type;
  }
}